spring.datasource.url=jdbc:postgresql://localhost:5432/checkout_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Habilitando o Hibernate para gerenciar o esquema e exibir os comandos SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações do Redis (mantém como está)
redis.host=localhost
redis.port=6379
redis.user=default
redis.password=SuaSenhaSuperSegura123