spring.datasource.url=jdbc:postgresql://localhost:5432/checkout_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

# Desativa a obrigatoriedade de ter arquivos HTML do Thymeleaf neste momento
spring.thymeleaf.check-template-location=false